/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 */

/*#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif
*/
#include <stdint.h>
#include "stm32f4xx.h"
//#include "core_cm4.h"
//#include ""
//#include "config.h"

//#include "hdr/hdr_rcc.h"
//#include "hdr/hdr_gpio.h"

//#include "gpio.h"
enum { SRAM_BB_REGION_START = 0x20000000 };
 enum { SRAM_BB_REGION_END = 0x200fffff };
 enum { SRAM_BB_ALIAS = 0x22000000 };
 enum { PERIPH_BB_REGION_START = 0x40000000 };
 enum { PERIPH_BB_REGION_END = 0x400fffff };
 enum { PERIPH_BB_ALIAS = 0x42000000 };
 #define SRAM_ADR_COND(adres) ( (uint32_t)&adres >= SRAM_BB_REGION_START && (uint32_t)&adres <=SRAM_BB_REGION_END )
 #define PERIPH_ADR_COND(adres) ( (uint32_t)&adres >= PERIPH_BB_REGION_START &&(uint32_t)&adres <= PERIPH_BB_REGION_END )
 #define BB_SRAM2(adres, bit) ( SRAM_BB_ALIAS + ((uint32_t)&adres -SRAM_BB_REGION_START)*32u + (uint32_t)(bit*4u) )
 #define BB_PERIPH(adres, bit) ( PERIPH_BB_ALIAS + ((uint32_t)&adres - PERIPH_BB_REGION_START)*32u + (uint32_t)(__builtin_ctz(bit))*4u)
 /* bit - bit mask, not bit position! */
 #define BB(adres, bit) *(__IO uint32_t *)( SRAM_ADR_COND(adres) ? BB_SRAM2(adres, bit) : \
 ( PERIPH_ADR_COND(adres) ? BB_PERIPH(adres, bit) : 0 ))

 #define BB_SRAM(adres, bit) *(__IO uint32_t *)BB_SRAM2(adres, bit)


#define CZESTOTLIWOSC 8000000
#define PB0 1<<0

void system_clk(void);
void GPIO_proc(void);
void delayMs(int n) ;



int main(void)
{

//	system_clk();
	/* Loop forever */
	GPIO_proc();
	SysTick_Config(CZESTOTLIWOSC);
	// gpio_pin_cfg(GPIOB, PB0, GPIO_OUT_PP_2MHz);
//gpio_init();
//gpio_pin_cfg(GPIOB, 1, GPIO_OUT_PP_2MHz);



	while (1) {
		/*delayMs(100);
		GPIOD->ODR|=(1<<13)|1<<14|1<<12|1<<15;
		delayMs(100);
		GPIOD->ODR &=~((1<<13)|1<<14|1<<12|1<<15);
		*/
	}

}

void system_clk(void)
{
RCC->CR|= RCC_CR_HSEON;


}
void GPIO_proc(void)
{
RCC->AHB1ENR|=RCC_AHB1ENR_GPIODEN|RCC_AHB1ENR_GPIOBEN|RCC_AHB1ENR_GPIOAEN;
GPIOD->MODER|=0x55000000; //0x4000000; //0x40;
GPIOD->ODR|=(1<<13)|1<<14|1<<12|1<<15;
GPIOB->MODER|=1;


}
void delayMs(int n)
{
    int i;
    for (; n > 0; n--)
        for (i = 0; i < 3195; i++) ;
}
__attribute__((interrupt)) void SysTick_Handler(void)
{
	GPIOD->ODR^=(1<<13)|1<<14|1<<12|1<<15;
	 BB(GPIOB->ODR, 1) ^= 1;

//GPIOB->ODR^=1;
}

